### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by MaxGsomGsom** [mtlazaro/cg_mrslam#7]
Firstly. I am trying to run algorithm with 2 robots and it seems that only matched nodes (and 10 of it's neighbors which sends in every ComboMessage) adds to graph. Am I right that this algorithm does not do merging of full graphs? Is there any ways to do that? As output I have some graphs in g2o format with some repeating nodes, so maybe there is some tool that can do it?

Secondly. Algorithm only can operate groups of 10 nodes that send in one ComboMessage. This number is hardcoded in variable
https://github.com/mtlazaro/cg_mrslam/blob/07e1fc49c2e5e7eca72f2532312ae25b14b2d1d1/src/mrslam/mr_graph_slam.cpp#L572
Am I right that increasing of this value will allow algorithm to match bigger parts of another robot's graph?

Thirdly. It seems that CondensedGraph messages sends continuously even if requested edges already was send in previous messages. It creates spam traffic. It can be connected with the fact that inClosures and outClosures don't delete from CondensedGraphBuffer after creating of CondensedGraph message.

**Comment by mtlazaro** [comment]
Hi @MaxGsomGsom,
I'll try to answer your questions.

1) Yes, only matched nodes from the other robot are added into the graph. These nodes are selected after a robust loop closure procedure to avoid wrong matches ruin one's robot graph. As it is described in the paper published from which this code, we don't transmit full graph but a condensed version of it containing only these matched nodes. This condensed measurements are enough to relate both maps. You can recover the joint graph by joining the g2o files into a single one (e.g., cat out1.g2o out2.g2o > joint.g2o), opening this g2o file with g2o_viewer and optimizing the full graph there. In the final.g2o file you have un "unfix" one of the origin vertices, as only one vertex should be fixed. 

2) The goal of this message is : 1) send last laser scan 2) update the estimates of the last N vertices. With this info the other robot reconstructs a local map for loop closure. Since the matching is done around the current vertex I don't think making N much bigger will help, instead will make computation of scan matching slower.

3) Yes, we continuously update the other robot when in range with the condensed graph requested, since it can change over time. Those structures maintain the information about which vertices we matched from the other robot (to request sending the condensed graph from them) and the vertices the other robot matched from our graph (we will need to send the condensed version from them).

I wish it is more clear now.

**Comment by MaxGsomGsom** [comment]
Thanks for answer. 

About CondensedGraph messages. Now I understand for what it required. But this messages send even if they contains the same data. I tried to run experiment and send only messages with different nodes and edges and it works as good as original version. So we can save a lot of traffic in situations where robots moves slow or have rare nodes' matches.

**Comment by mtlazaro** [comment]
I understand what you mean. And in most of the cases, the information sent is practically the same. Hovewer, info contained in the condensed edges that are sent could have importantly changed in the case of a loop closure in its own graph. One could check this by looking at the residual error after the graph optimization.
